# Generated by Django 5.2.9 on 2025-12-08 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='context',
            name='text',
            field=models.TextField(max_length=300),
        ),
    ]
