# Generated by Django 5.2.9 on 2025-12-08 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_context_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='context',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='articles/context'),
        ),
    ]
